### ISSUE TITLE
boxes>Byte is not mapped to java.lang.byte

### ISSUE THREAD

**Issue by arturbosch** [kosi-libs/Kodein-Type#3]
Hi,

was just reading the source code here on GitHub and stumbled upon:

https://github.com/Kodein-Framework/Kodein-Type/blob/master/kodein-type/src/jvmMain/kotlin/org/kodein/type/typeTokensJVM.kt#L15

I was asking myself if this was intented or a typo?

All boxes mapping lead to a corresponding java.lang class except Byte.

```kotlin
private val boxes = mapOf(
        Boolean::class.java to java.lang.Boolean::class.java,
        Byte::class.java to Byte::class.java,
        Char::class.java to java.lang.Character::class.java,
        Short::class.java to java.lang.Short::class.java,
        Int::class.java to java.lang.Integer::class.java,
        Long::class.java to java.lang.Long::class.java,
        Float::class.java to java.lang.Float::class.java,
        Double::class.java to java.lang.Double::class.java
)
```

Note: I haven't found a testcase for boxes in jvmTest.

**Comment by romainbsl** [comment]
Certainly is. It will be merged soon. Thanks for the report 👍
