### ISSUE TITLE
Add proguard rules to avoid dead code elimination

### ISSUE THREAD

**Issue by romainbsl** [kosi-libs/Kodein-Type#6]
from https://github.com/Kodein-Framework/Kodein-DI/issues/309

```
-keep, allowobfuscation, allowoptimization class org.kodein.type.TypeReference
-keep, allowobfuscation, allowoptimization class org.kodein.type.JVMAbstractTypeToken$Companion$WrappingTest

-keep, allowobfuscation, allowoptimization class * extends org.kodein.type.TypeReference
-keep, allowobfuscation, allowoptimization class * extends org.kodein.type.JVMAbstractTypeToken$Companion$WrappingTest
```

**Comment by slavonnet** [comment]
Some issue with 7.8.0;. Need manual add rules

**Comment by eygraber** [comment]
@romainbsl any chance this will ever get added?

**Comment by romainbsl** [comment]
@eygraber I am sorry about the delay on that one. And honestly kinda forgot about it. I should be able to do it by the end of February.

**Comment by romainbsl** [comment]
@eygraber I did publish a snapshot version of **Kaverit**, under the version `2.4.0-android-proguard-SNAPSHOT`, so that the `.aar` embed a proguard.txt file to be merged with the one in an application.

I also published a snapshot of **Kodein** that embed that specific version of **Kaverit**, `7.20.0-kaverit-proguard-rules-SNAPSHOT`.

I didn't try those, but I guess that you can easily try this on your own projects.

**Comment by eygraber** [comment]
Thanks, I'll try that when I get a chance.

**Comment by mujahid-iitr** [comment]
For someone who is still struggling, try this:
-keep, allowobfuscation, allowoptimization class org.kodein.di.TypeReference
-keep, allowobfuscation, allowoptimization class * extends org.kodein.di.TypeReference

**Comment by romainbsl** [comment]
`org.kodein.di.TypeReference` has been removed since a long time!
Almost, since this library exists.

**Comment by romainbsl** [comment]
Published within v.2.7.0
