### ISSUE TITLE
Binding type parameter

### ISSUE THREAD

**Issue by nsragow** [kosi-libs/Kodein-Type#8]
I can't figure out a way to bind a type parameter:

```
class Container<Type>(val obj: Type) {
    fun typeBinder(builder: Kodein.Builder) {
        builder.apply { 
            bind() from singleton { obj }
        }
    }
}
```

Is this possible?

**Comment by nsragow** [comment]
I came up with a workaround: 

```
class Container<Type : Any>(val obj: Type, val klass: KClass<Type>) {
    fun typeBinder(builder: Kodein.Builder) {
        builder.apply {
            val s = Singleton(
                scope,
                contextType,
                TT(klass),
                null,
                true,
            ) {
                obj
            }
            bind() from s
        }
    }
}
```

Not sure if this is how I am supposed to be using this though.

**Comment by romainbsl** [comment]
Hi, what are you trying to bind really ? (I guess that your are working with [Kodein](https://github.com/kosi-libs/Kodein) (you are on Kaverit repo here).

Kodein should have everything you need. If you are trying to bind an existing object, you can do:

```kotlin
class Foo

val obj = Foo()

val di = DI {
 bindInstance { obj }
}

val injectedFoo : Foo by di.instance()

assert(obj == injectedFoo)
```

**Comment by nsragow** [comment]
O sorry my bad, I'll post to the Kodein repo

**Comment by romainbsl** [comment]
duplicate: https://github.com/kosi-libs/Kodein/issues/449
