### ISSUE TITLE
Support `Any?`

### ISSUE THREAD

**Issue by mgroth0** [kosi-libs/Kodein-Type#9]
I am curious why the extension functions all have an upper bound of `Any`.

I am exploring possible use cases of this library. I scanned through my code to see where I used `typeOf` and wanted to play around with if this library could benefit those places. But in those places I have an upper bound of `Any?`. 

I am not quite sure if I have a use for this library but it looks interesting, so I figured I would just ask if this constraint is necessary.

**Comment by SalomonBrys** [comment]
The goal of this lib is to provide multiplatform reflection **without** `kotlin-reflect` on the JVM (mainly because it is too big to be included in an Android app).
We therefore use the JVM reflection API that is part of the runtime, which does not support nullable types.

**Comment by mgroth0** [comment]
Thank you for the answer.

Is there any collection of small examples, demos, or use cases for this library? I am trying to learn where it fits. 

In particular, showing what it offers that kotlin-stdlib does not offer on its own?

**Comment by romainbsl** [comment]
This library is mostly used by our Dependency Injection library, [Kodein](https://github.com/kosi-libs/Kodein/tree/master).
You can find usages [here](https://github.com/kosi-libs/Kodein/tree/7bf22a71b66c52e6434c72e6162377b10085567f/kodein-di/src/commonMain/kotlin/org/kodein/di) in the `bind*` files.
